[package]
name = "back-end"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
actix-cors = "0.7.1"
serde = "1.0.219"
thiserror = "2.0.12"
bcrypt = "0.17.0"
actix = "0.13.5"
dotenv = "0.15.0"
sqlx = {version = "0.8.6", features = ["postgres", "runtime-async-std"]}